version: '3.7'

services:
  postgres-database:
    image: postgres:15
    restart: always
    container_name: postgres-database
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
  synapse:
    build:
      context: ./docker
      dockerfile: Dockerfile.synapse
    restart: always
    volumes:
      - ./data:/data
      - ./start.sh:/start.sh
    environment:
      - SYNAPSE_SERVER_NAME=localhost
      - SYNAPSE_REPORT_STATS=no
      - SYNAPSE_DATABASE_TYPE=postgres
      - SYNAPSE_POSTGRES_HOST=postgres-database
      - SYNAPSE_POSTGRES_USER=synapse_user
      - SYNAPSE_POSTGRES_PASSWORD=synapse_pass
      - SYNAPSE_POSTGRES_DB=synapse
    depends_on:
      - postgres-database
    ports:
      - '8808:8008'
      - '8848:8448'
    entrypoint: ['/start.sh']
  redis:
    image: redis:latest
    container_name: redis-cache
    env_file:
      - .env
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    environment:
      - REDIS_REPLICATION_MODE=master
    volumes:
      - redis_data:/data
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - backend

volumes:
  postgres_data:
  synapse_data:
  redis_data:

networks:
  backend:
    name: backend_network
